eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_DISCOVERY_ADDRESS}
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true