spring:
  application:
    name: second-business-service
server:
  servlet:
    context-path: /second
resilience4j:
  circuitbreaker:
    instances:
      first-business-service-caller:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED