management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tracing-backend:9411/api/v2/spans
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


#2023-07-01 23:39:04 2023-07-01T21:39:04.887Z  INFO [first-business-service,64a09cf8ad84d2a3d575bac1ae0c6461,edce66fb8cc91019] 1 --- [nio-8080-exec-2] e.d.s.c.FirstBusinessServiceController   : Call received!